version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: cloud_postgres
    environment:
      POSTGRES_DB: cloud_db
      POSTGRES_USER: cloud_user
      POSTGRES_PASSWORD: cloud_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cloud_user -d cloud_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  minio:
    image: minio/minio
    container_name: minio_server
    hostname: minio
    ports:
      - "9000:9000"  # API порт
      - "9001:9001"  # Консоль управления
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=admin      # Логин администратора
      - MINIO_ROOT_PASSWORD=password  # Пароль администратора (замените на сложный)
    command: server /data --console-address ":9001"
    restart: unless-stopped

volumes:
  postgres_data:
  minio_data:
